Task List

In [8]:
# Task Name, From, Date, Type

# Hang Lung Amoy Plaza and Fashion Walk LMS Figures, Mandy Chan, 20260929, M_Report
# TA Cancel Order Daily Report (auto gen), Carrie Yeung, 20260928, Report Script
# Restaurant List, Dish/Amenity categories, Manson Ma, 20260928, Report
# AML decryption, Manson Ma, 20260922, Request
# TA Cancallation Time Distribution by Customer (Jun-Sep), Mandy Ip, 20260929, M_Report
# IOS Version Active User, Tom Yuen, 20260925, Report
# LSLS Report, Tom Yuen, 20260921 and 20261002, M_Report
# TA PickUpTime Hourly Breakdown, Mandy Ip, 20260921, M_Report
# TA AcceptedTime Distribution, Manson Ma, 20260922, Request
# TA Funneling Analysis (entry source & drop point), Manson Ma, 20260917, Request
# Voucher & Book-with-menu User and POI List, Angela Pang, 20260907, Request
# SG_Booking_Postpaid_Monthly_Report (Aug 2026) --> misssing enum, Grace Xu, 20260909, Email
# Booking Fulfillment 8月特選訂座餐廳, Angela Pang, 20260910, M_Report
# TA General Report (P90), Jonathan, 20260909, Report
# POI Booking List over the past 3 months in Quarry Bay & North Point, Vesta Ling, 20260910, Report
# Data for Media Kit, Lily Lin, 20260915, M_Report
# Book-with-Menu User list, Joyce Chan, 20260914, Request
# Resource, Kimmy Lam, 20260915, Resource
# Booking Service Analysis, Joe Yau, 20260916, Request
# POI list: same address, status = active & renovate, Clement Lui, 20260916, Request
# Booking Festival Email Mapping, Joyce Chan, 20261005, Request
# Pet Report, Tom Yuen, 20261005, M_Report
# Data Team Sino Monthly LMS Report (Figure + List), Tom Yuen, 20261005, M_Report
# TA Merchant Offline Alert Report, Mandy Ip, 20261005, Email
# Report for gingersoft Restaurant, Ken Ma, 20261008, Request

# change to df and then sort by task name
import pandas as pd

data = [
    ["Hang Lung Amoy Plaza and Fashion Walk LMS Figures", "Mandy Chan", "20260929", "M_Report"],
    ["TA Cancel Order Daily Report (auto gen)", "Carrie Yeung", "20260928", "Report"],
    ["Restaurant List, Dish/Amenity categories", "Manson Ma", "20260928", "Report"],
    ["AML decryption", "Manson Ma", "20260922", "Request"],
    ["TA Cancallation Time Distribution by Customer (Jun-Sep)", "Mandy Ip", "20260929", "M_Report"],
    ["IOS Version Active User", "Tom Yuen", "20260925", "Report"],
    ["LSLS Report", "Tom Yuen", "20260921", "M_Report"],
    ["TA PickUpTime Hourly Breakdown", "Mandy Ip", "20260921", "M_Report"],
    ["TA AcceptedTime Distribution", "Manson Ma", "20260922", "Request"],
    ["TA Funneling Analysis (entry source & drop point)", "Manson Ma", "20260917", "Request"],
    ["Voucher & Book-with-menu User and POI List", "Angela Pang", "20260907", "Request"],
    ["SG_Booking_Postpaid_Monthly_Report (Aug 2026) --> misssing enum", "Grace Xu", "20260909", "Email"],
    ["Booking Fulfillment 8月特選訂座餐廳", "Angela Pang", "20260910", "M_Report"],
    ["TA General Report (P90)", "Jonathan", "20260909", "Report"],
    ["POI Booking List over the past 3 months in Quarry Bay & North Point", "Vesta Ling", "20260910", "Report"],
    ["Data for Media Kit", "Lily Lin", "20260915", "M_Report"],
    ["Book-with-Menu User list", "Joyce Chan", "20260914", "M_Report"],
    ["Resource", "Kimmy Lam", "20260915", "Resource"],
    ["Booking Service Analysis", "Joe Yau", "20260916", "Request"],
    ["POI list: same address, status = active & renovate", "Clement Lui", "20260916", "Request"],
    ["Booking Festival Email Mapping", "Joyce Chan", "20261005", "Request"],
    ["Pet Report", "Tom Yuen", "20261005", "M_Report"],
    ["Data Team Sino Monthly LMS Report (Figure + List)", "Tom Yuen", "20261005", "M_Report"],
    ["TA Merchant Offline Alert Report", "Mandy Ip", "20261005", "Email"],
    ["Report for gingersoft Restaurant", "Ken Ma", "20261008", "Request"],

]

df = pd.DataFrame(data, columns=["Task Name", "From", "Date", "Type"])
df = df.sort_values(by="Task Name")
df["Date"] = pd.to_datetime(df["Date"])
df

,Task Name,From,Date,Type
3,AML decryption,Manson Ma,2026-09-22,Request
16,Book-with-Menu User list,Joyce Chan,2026-09-14,M_Report
20,Booking Festival Email Mapping,Joyce Chan,2026-10-05,Request
12,Booking Fulfillment 8月特選訂座餐廳,Angela Pang,2026-09-10,M_Report
18,Booking Service Analysis,Joe Yau,2026-09-16,Request
22,Data Team Sino Monthly LMS Report (Figure + List),Tom Yuen,2026-10-05,M_Report
15,Data for Media Kit,Lily Lin,2026-09-15,M_Report
0,Hang Lung Amoy Plaza and Fashion Walk LMS Figures,Mandy Chan,2026-09-29,M_Report
5,IOS Version Active User,Tom Yuen,2026-09-25,Report
6,LSLS Report,Tom Yuen,2026-09-21,M_Report
14,POI Booking List over the past 3 months in Qua...,Vesta Ling,2026-09-10,Report
19,"POI list: same address, status = active & reno...",Clement Lui,2026-09-16,Request
21,Pet Report,Tom Yuen,2026-10-05,M_Report
24,Report for gingersoft Restaurant,Ken Ma,2026-10-08,Request
17,Resource,Kimmy Lam,2026-09-15,Resource
2,"Restaurant List, Dish/Amenity categories",Manson Ma,2026-09-28,Report
11,SG_Booking_Postpaid_Monthly_Report (Aug 2026) ...,Grace Xu,2026-09-09,Email
8,TA AcceptedTime Distribution,Manson Ma,2026-09-22,Request
4,TA Cancallation Time Distribution by Customer ...,Mandy Ip,2026-09-29,M_Report
1,TA Cancel Order Daily Report (auto gen),Carrie Yeung,2026-09-28,Report
9,TA Funneling Analysis (entry source & drop point),Manson Ma,2026-09-17,Request
13,TA General Report (P90),Jonathan,2026-09-09,Report
23,TA Merchant Offline Alert Report,Mandy Ip,2026-10-05,Email
7,TA PickUpTime Hourly Breakdown,Mandy Ip,2026-09-21,M_Report
10,Voucher & Book-with-menu User and POI List,Angela Pang,2026-09-07,Request

In [9]:
df_1 = df[df["Type"] == "M_Report"]
df_1 = df_1.sort_values(by="Date")
df_1

,Task Name,From,Date,Type
12,Booking Fulfillment 8月特選訂座餐廳,Angela Pang,2026-09-10,M_Report
16,Book-with-Menu User list,Joyce Chan,2026-09-14,M_Report
15,Data for Media Kit,Lily Lin,2026-09-15,M_Report
6,LSLS Report,Tom Yuen,2026-09-21,M_Report
7,TA PickUpTime Hourly Breakdown,Mandy Ip,2026-09-21,M_Report
0,Hang Lung Amoy Plaza and Fashion Walk LMS Figures,Mandy Chan,2026-09-29,M_Report
4,TA Cancallation Time Distribution by Customer ...,Mandy Ip,2026-09-29,M_Report
22,Data Team Sino Monthly LMS Report (Figure + List),Tom Yuen,2026-10-05,M_Report
21,Pet Report,Tom Yuen,2026-10-05,M_Report

In [ ]:
# LSLS & Foodwise:
#  http://192.168.61.59:8888/notebooks/reports/monthly_icon_impression_report/monthly_icon_impression_report_result.ipynb

# Booking Report (Looker Studio):
# https://datastudio.google.com/u/0/reporting/7c3b023f-409e-4ef4-9320-3f97f6558830/page/JcsMC

# Bookmore Report:
# http://192.168.61.59:8888/tree/reports/Bookmore_Report

# GPT:
# http://internal.chatgpt.openrice.com/#/chat
# Password: P@ssw0rd

# Airflow:
# dags: http://192.168.61.59:8888/tree/dags
# Auto Gen Report Step:
# 1. write ipynb script （db.ipynb --> sql --> gen excel --> def send email --> send to who）
# 2. upload to report:  http://192.168.61.59:8888/tree/reports
# 3. write dags:   http://192.168.61.59:8888/tree/dags
# 4. airflow: set time to test

# Email Mapping:
# create folder: email mapping --> upload excel & email_mapping.ipynb to the path
# http://172.17.2.220:8888/tree/Birthday

# GPU2 - Tom: http://172.17.2.220:8888/tree/Tom
#        Dan: http://172.17.2.220:8888/tree/Dan    -->   BQ/BQ2

# my softlink workplace: http://192.168.61.59:8888/tree/reports/soft_link_lenalee

In [ ]:
# ??
# 展開df所有列：
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

df


# C:\Windows\System32\drivers\etc\host
# 192.168.61.36 mcp.python.openrice.com
#  {
#     "servers": {
#         "openrice": {
#             "type": "http",
#             "url": "http://mcp.python.openrice.com/mcp"
#         }
#     }
# }