In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

/tmp/ipykernel_5223/3777615979.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

In [2]:
import datetime as dt
import pandas as pd
import pymssql
DB_info = {'server':'192.168.61.119:7622', 'user':'BAReporting', 'password':'KeHeCReme8he'}

In [3]:
# start_date = dt.date(2025,12,1)
# end_date = dt.date(2025,12,31)
# start_date, end_date

In [4]:
# start_date = (dt.date.today().replace(day=1) - dt.timedelta(days=1)).replace(day=1)
# end_date = dt.date.today()
# start_date, end_date

In [5]:
start_date = (dt.date.today().replace(day=1) - dt.timedelta(days=1)).replace(day=1)
end_date = dt.date.today().replace(day=1) - dt.timedelta(days=1)
start_date, end_date

(datetime.date(2026, 7, 1), datetime.date(2026, 7, 31))

In [6]:
# start_date = dt.date(2024, 5, 21)
# end_date = dt.date(2024, 5, 31)
# start_date, end_date

# check bookmore offerid every month

In [7]:
###check bookmore offerid every month

# SELECT *
 
#   FROM [Mars].[dbo].[Offer] (nolock)
#   where TitleLang1 like '%bookmore%' and StartTime<='2025-02-01' and endtime>='2025-03-01'
#427088 2024 12 月
# 407255 is 2024 8月
# 417523
# 403947
# 355340
offerid = (430536) # eatmore
#bookmore no need offerid now

In [8]:
#print(select_sql)

In [9]:
with pymssql.connect(DB_info['server'], DB_info['user'], DB_info['password'], 'mars') as conn:
    cursor = conn.cursor()
    select_sql = f'''
    WITH 
--    booking_offer as (
--    SELECT distinct b.bookingid, o.offerid, o.TitleLang1 from booking b (NOLOCK)
--    LEFT JOIN offerwallet ow (NOLOCK) on b.bookingid = ow.bookingid
--    LEFT JOIN offer o (NOLOCK) on o.offerid = ow.offerid
--    left join poi p (NOLOCK) on b.poiid = p.poiid
--    left join openrice3.dbo.poi op (NOLOCK) on p.orpoiid = op.poiid
--    where ow.status=15 and b.status=10 and o.offerid in () and b.userid!=0
--    and convert(date, b.bookingtime) between '{start_date}' and '{end_date}'
--  and convert(date, b.submittime) between '{start_date}' and '{end_date}'
--    and p.status not in (2,6)
--    ),
    
    booking_menu as (
    SELECT bmo.bookingid, sum(bpt.FinalPrice) as bookmenu_spending from BookingMenuOrder bmo (nolock)
    left join booking b on bmo.bookingid = b.bookingid
    left join BookingPaymentTransaction bpt (nolock) on bmo.bookingid = bpt.bookingid
    left join poi p on p.poiid = b.poiid
    where bmo.status in (15) and bpt.PaymentStatus=10 and bpt.BookingPaymentTransactionType=1
    and convert(date, b.bookingtime) between '{start_date}' and '{end_date}'
 --   and convert(date, b.submittime) between '{start_date}' and '{end_date}'
    and regionid = 0
    group by bmo.bookingid
    )
    
    SELECT  b.poiid as RestaurantID, p.namelang1 as RestaurantName, b.BookingRefId, b.userid as mars_userid,
    b.SubmitTime, convert(date,b.BookingTime) as BookingDate, convert(time, timeslottime) as BookingTime,
    iif(b.userid in (SELECT userid from booking (nolock) 
                     where status=4 
                     and convert(date, bookingtime) between '{start_date}' and '{end_date}'
                   --  and convert(date, submittime) between '{start_date}' and '{end_date}'
                   ), 'Y', 'N') as hv_noshow,
    b.AmendedSeat, bookmenu_spending 
    from booking b (NOLOCK)
    left join poi p (NOLOCK) on b.poiid = p.poiid
    left join timeslot ts (NOLOCK) on b.StartTimeSlotId = ts.timeslotid
    left join booking_menu bm on b.bookingid = bm.bookingid
--    right join booking_offer bo on b.bookingid = bo.bookingid
    where p.status not in (2,6) and p.regionid=0 and b.userid!=0 and b.status=10
    and convert(date, b.bookingtime) between '{start_date}' and '{end_date}'
  --  and convert(date, b.submittime) between '{start_date}' and '{end_date}'
    and p.regionid = 0
    order by b.userid , b.bookingid
    '''
    df = pd.read_sql(select_sql, conn)

/home/airflow/anaconda3/envs/report/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [10]:
df['BookingDateTime'] = df[['BookingDate', 'BookingTime']].apply(lambda x: dt.datetime.combine(x[0], x[1]), axis=1)
df

,RestaurantID,RestaurantName,BookingRefId,mars_userid,SubmitTime,BookingDate,BookingTime,hv_noshow,AmendedSeat,bookmenu_spending,BookingDateTime
0,19826,後街牛扒,20260718065025,111,2026-07-18 18:24:40.597,2026-07-21,19:30:00,N,2,NaN,2026-07-21 19:30:00
1,27535,牛大人台灣火鍋吃到飽,20260721125459,114,2026-07-21 20:55:16.980,2026-07-23,11:30:00,N,2,NaN,2026-07-23 11:30:00
2,97080,Basic Bistro,20260718069701-1,127,2026-07-19 17:05:52.500,2026-07-19,20:30:00,N,2,NaN,2026-07-19 20:30:00
3,50493,喫茶ちょうぼ,20260710897474,132,2026-07-10 17:52:26.830,2026-07-11,15:30:00,N,4,NaN,2026-07-11 15:30:00
4,120282,Cooshti,20260729272886,142,2026-07-29 12:45:06.267,2026-07-29,18:30:00,N,5,NaN,2026-07-29 18:30:00
...,...,...,...,...,...,...,...,...,...,...,...
352062,52312,大滾友火鍋,20260731324491,7646559,2026-07-31 19:37:18.760,2026-07-31,20:00:00,N,3,NaN,2026-07-31 20:00:00
352063,125297,GOLDEN CAFE,20260731324521,7646562,2026-07-31 19:38:16.797,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00
352064,93695,九五至尊火鍋狗毛,20260731326922-1,7646610,2026-07-31 21:54:10.370,2026-07-31,23:00:00,N,3,NaN,2026-07-31 23:00:00
352065,31944,KABOOM,20260731325255,7646636,2026-07-31 20:11:51.790,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00
352066,25507,李家,20260731325572,7646693,2026-07-31 20:30:40.663,2026-07-31,22:00:00,N,2,NaN,2026-07-31 22:00:00

In [11]:
df[['RestaurantID', 'mars_userid', 'BookingDateTime']].groupby(['RestaurantID', 'mars_userid']).rank()

        BookingDateTime
0                   1.0
1                   1.0
2                   1.0
3                   1.0
4                   1.0
...                 ...
352062              1.0
352063              1.0
352064              1.0
352065              1.0
352066              1.0

[352067 rows x 1 columns]

In [12]:
import datetime as dt
### rank the booking times that the users booked the same poi
df['BookingDateTime'] = df[['BookingDate', 'BookingTime']].apply(lambda x: str(x[0]) + ' ' + str(x[1]), axis=1)
gg = df[['RestaurantID', 'mars_userid', 'BookingDateTime']].groupby(['RestaurantID', 'mars_userid']).rank()
gg.columns = ['Rank']
gg

        Rank
0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
...      ...
352062   1.0
352063   1.0
352064   1.0
352065   1.0
352066   1.0

[352067 rows x 1 columns]

In [13]:
df = pd.concat([df, gg], axis=1)
df

,RestaurantID,RestaurantName,BookingRefId,mars_userid,SubmitTime,BookingDate,BookingTime,hv_noshow,AmendedSeat,bookmenu_spending,BookingDateTime,Rank
0,19826,後街牛扒,20260718065025,111,2026-07-18 18:24:40.597,2026-07-21,19:30:00,N,2,NaN,2026-07-21 19:30:00,1.0
1,27535,牛大人台灣火鍋吃到飽,20260721125459,114,2026-07-21 20:55:16.980,2026-07-23,11:30:00,N,2,NaN,2026-07-23 11:30:00,1.0
2,97080,Basic Bistro,20260718069701-1,127,2026-07-19 17:05:52.500,2026-07-19,20:30:00,N,2,NaN,2026-07-19 20:30:00,1.0
3,50493,喫茶ちょうぼ,20260710897474,132,2026-07-10 17:52:26.830,2026-07-11,15:30:00,N,4,NaN,2026-07-11 15:30:00,1.0
4,120282,Cooshti,20260729272886,142,2026-07-29 12:45:06.267,2026-07-29,18:30:00,N,5,NaN,2026-07-29 18:30:00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
352062,52312,大滾友火鍋,20260731324491,7646559,2026-07-31 19:37:18.760,2026-07-31,20:00:00,N,3,NaN,2026-07-31 20:00:00,1.0
352063,125297,GOLDEN CAFE,20260731324521,7646562,2026-07-31 19:38:16.797,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0
352064,93695,九五至尊火鍋狗毛,20260731326922-1,7646610,2026-07-31 21:54:10.370,2026-07-31,23:00:00,N,3,NaN,2026-07-31 23:00:00,1.0
352065,31944,KABOOM,20260731325255,7646636,2026-07-31 20:11:51.790,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0
352066,25507,李家,20260731325572,7646693,2026-07-31 20:30:40.663,2026-07-31,22:00:00,N,2,NaN,2026-07-31 22:00:00,1.0

In [14]:
new_df = df[df.Rank == 1]
new_df

,RestaurantID,RestaurantName,BookingRefId,mars_userid,SubmitTime,BookingDate,BookingTime,hv_noshow,AmendedSeat,bookmenu_spending,BookingDateTime,Rank
0,19826,後街牛扒,20260718065025,111,2026-07-18 18:24:40.597,2026-07-21,19:30:00,N,2,NaN,2026-07-21 19:30:00,1.0
1,27535,牛大人台灣火鍋吃到飽,20260721125459,114,2026-07-21 20:55:16.980,2026-07-23,11:30:00,N,2,NaN,2026-07-23 11:30:00,1.0
2,97080,Basic Bistro,20260718069701-1,127,2026-07-19 17:05:52.500,2026-07-19,20:30:00,N,2,NaN,2026-07-19 20:30:00,1.0
3,50493,喫茶ちょうぼ,20260710897474,132,2026-07-10 17:52:26.830,2026-07-11,15:30:00,N,4,NaN,2026-07-11 15:30:00,1.0
4,120282,Cooshti,20260729272886,142,2026-07-29 12:45:06.267,2026-07-29,18:30:00,N,5,NaN,2026-07-29 18:30:00,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
352062,52312,大滾友火鍋,20260731324491,7646559,2026-07-31 19:37:18.760,2026-07-31,20:00:00,N,3,NaN,2026-07-31 20:00:00,1.0
352063,125297,GOLDEN CAFE,20260731324521,7646562,2026-07-31 19:38:16.797,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0
352064,93695,九五至尊火鍋狗毛,20260731326922-1,7646610,2026-07-31 21:54:10.370,2026-07-31,23:00:00,N,3,NaN,2026-07-31 23:00:00,1.0
352065,31944,KABOOM,20260731325255,7646636,2026-07-31 20:11:51.790,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0
352066,25507,李家,20260731325572,7646693,2026-07-31 20:30:40.663,2026-07-31,22:00:00,N,2,NaN,2026-07-31 22:00:00,1.0

In [15]:
new_df['BookingDateTime_Restaurant'] = new_df[['BookingDateTime', 'RestaurantID']].apply(lambda x: '%s (%d)' % (x[0], x[1]), axis=1)
new_df

/tmp/ipykernel_5223/3999145735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['BookingDateTime_Restaurant'] = new_df[['BookingDateTime', 'RestaurantID']].apply(lambda x: '%s (%d)' % (x[0], x[1]), axis=1)

,RestaurantID,RestaurantName,BookingRefId,mars_userid,SubmitTime,BookingDate,BookingTime,hv_noshow,AmendedSeat,bookmenu_spending,BookingDateTime,Rank,BookingDateTime_Restaurant
0,19826,後街牛扒,20260718065025,111,2026-07-18 18:24:40.597,2026-07-21,19:30:00,N,2,NaN,2026-07-21 19:30:00,1.0,2026-07-21 19:30:00 (19826)
1,27535,牛大人台灣火鍋吃到飽,20260721125459,114,2026-07-21 20:55:16.980,2026-07-23,11:30:00,N,2,NaN,2026-07-23 11:30:00,1.0,2026-07-23 11:30:00 (27535)
2,97080,Basic Bistro,20260718069701-1,127,2026-07-19 17:05:52.500,2026-07-19,20:30:00,N,2,NaN,2026-07-19 20:30:00,1.0,2026-07-19 20:30:00 (97080)
3,50493,喫茶ちょうぼ,20260710897474,132,2026-07-10 17:52:26.830,2026-07-11,15:30:00,N,4,NaN,2026-07-11 15:30:00,1.0,2026-07-11 15:30:00 (50493)
4,120282,Cooshti,20260729272886,142,2026-07-29 12:45:06.267,2026-07-29,18:30:00,N,5,NaN,2026-07-29 18:30:00,1.0,2026-07-29 18:30:00 (120282)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
352062,52312,大滾友火鍋,20260731324491,7646559,2026-07-31 19:37:18.760,2026-07-31,20:00:00,N,3,NaN,2026-07-31 20:00:00,1.0,2026-07-31 20:00:00 (52312)
352063,125297,GOLDEN CAFE,20260731324521,7646562,2026-07-31 19:38:16.797,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,2026-07-31 21:00:00 (125297)
352064,93695,九五至尊火鍋狗毛,20260731326922-1,7646610,2026-07-31 21:54:10.370,2026-07-31,23:00:00,N,3,NaN,2026-07-31 23:00:00,1.0,2026-07-31 23:00:00 (93695)
352065,31944,KABOOM,20260731325255,7646636,2026-07-31 20:11:51.790,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,2026-07-31 21:00:00 (31944)
352066,25507,李家,20260731325572,7646693,2026-07-31 20:30:40.663,2026-07-31,22:00:00,N,2,NaN,2026-07-31 22:00:00,1.0,2026-07-31 22:00:00 (25507)

In [16]:
### only take poi's first-time booking to rank bookingtime by pois
gg = new_df[['mars_userid', 'BookingDateTime_Restaurant']].groupby('mars_userid').rank()
gg.columns = ['Rank2']
gg

        Rank2
0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
...       ...
352062    1.0
352063    1.0
352064    1.0
352065    1.0
352066    1.0

[341240 rows x 1 columns]

In [17]:
new_df = pd.concat([new_df, gg], axis=1)
new_df

,RestaurantID,RestaurantName,BookingRefId,mars_userid,SubmitTime,BookingDate,BookingTime,hv_noshow,AmendedSeat,bookmenu_spending,BookingDateTime,Rank,BookingDateTime_Restaurant,Rank2
0,19826,後街牛扒,20260718065025,111,2026-07-18 18:24:40.597,2026-07-21,19:30:00,N,2,NaN,2026-07-21 19:30:00,1.0,2026-07-21 19:30:00 (19826),1.0
1,27535,牛大人台灣火鍋吃到飽,20260721125459,114,2026-07-21 20:55:16.980,2026-07-23,11:30:00,N,2,NaN,2026-07-23 11:30:00,1.0,2026-07-23 11:30:00 (27535),1.0
2,97080,Basic Bistro,20260718069701-1,127,2026-07-19 17:05:52.500,2026-07-19,20:30:00,N,2,NaN,2026-07-19 20:30:00,1.0,2026-07-19 20:30:00 (97080),1.0
3,50493,喫茶ちょうぼ,20260710897474,132,2026-07-10 17:52:26.830,2026-07-11,15:30:00,N,4,NaN,2026-07-11 15:30:00,1.0,2026-07-11 15:30:00 (50493),1.0
4,120282,Cooshti,20260729272886,142,2026-07-29 12:45:06.267,2026-07-29,18:30:00,N,5,NaN,2026-07-29 18:30:00,1.0,2026-07-29 18:30:00 (120282),1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352062,52312,大滾友火鍋,20260731324491,7646559,2026-07-31 19:37:18.760,2026-07-31,20:00:00,N,3,NaN,2026-07-31 20:00:00,1.0,2026-07-31 20:00:00 (52312),1.0
352063,125297,GOLDEN CAFE,20260731324521,7646562,2026-07-31 19:38:16.797,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,2026-07-31 21:00:00 (125297),1.0
352064,93695,九五至尊火鍋狗毛,20260731326922-1,7646610,2026-07-31 21:54:10.370,2026-07-31,23:00:00,N,3,NaN,2026-07-31 23:00:00,1.0,2026-07-31 23:00:00 (93695),1.0
352065,31944,KABOOM,20260731325255,7646636,2026-07-31 20:11:51.790,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,2026-07-31 21:00:00 (31944),1.0
352066,25507,李家,20260731325572,7646693,2026-07-31 20:30:40.663,2026-07-31,22:00:00,N,2,NaN,2026-07-31 22:00:00,1.0,2026-07-31 22:00:00 (25507),1.0

In [18]:
new_df['Target_Time'] = new_df[['Rank2', 'BookingDateTime']].apply(lambda x: x[1] if x[0] % 3 == 0 else '', axis=1)
new_df

,RestaurantID,RestaurantName,BookingRefId,mars_userid,SubmitTime,BookingDate,BookingTime,hv_noshow,AmendedSeat,bookmenu_spending,BookingDateTime,Rank,BookingDateTime_Restaurant,Rank2,Target_Time
0,19826,後街牛扒,20260718065025,111,2026-07-18 18:24:40.597,2026-07-21,19:30:00,N,2,NaN,2026-07-21 19:30:00,1.0,2026-07-21 19:30:00 (19826),1.0,
1,27535,牛大人台灣火鍋吃到飽,20260721125459,114,2026-07-21 20:55:16.980,2026-07-23,11:30:00,N,2,NaN,2026-07-23 11:30:00,1.0,2026-07-23 11:30:00 (27535),1.0,
2,97080,Basic Bistro,20260718069701-1,127,2026-07-19 17:05:52.500,2026-07-19,20:30:00,N,2,NaN,2026-07-19 20:30:00,1.0,2026-07-19 20:30:00 (97080),1.0,
3,50493,喫茶ちょうぼ,20260710897474,132,2026-07-10 17:52:26.830,2026-07-11,15:30:00,N,4,NaN,2026-07-11 15:30:00,1.0,2026-07-11 15:30:00 (50493),1.0,
4,120282,Cooshti,20260729272886,142,2026-07-29 12:45:06.267,2026-07-29,18:30:00,N,5,NaN,2026-07-29 18:30:00,1.0,2026-07-29 18:30:00 (120282),1.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352062,52312,大滾友火鍋,20260731324491,7646559,2026-07-31 19:37:18.760,2026-07-31,20:00:00,N,3,NaN,2026-07-31 20:00:00,1.0,2026-07-31 20:00:00 (52312),1.0,
352063,125297,GOLDEN CAFE,20260731324521,7646562,2026-07-31 19:38:16.797,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,2026-07-31 21:00:00 (125297),1.0,
352064,93695,九五至尊火鍋狗毛,20260731326922-1,7646610,2026-07-31 21:54:10.370,2026-07-31,23:00:00,N,3,NaN,2026-07-31 23:00:00,1.0,2026-07-31 23:00:00 (93695),1.0,
352065,31944,KABOOM,20260731325255,7646636,2026-07-31 20:11:51.790,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,2026-07-31 21:00:00 (31944),1.0,
352066,25507,李家,20260731325572,7646693,2026-07-31 20:30:40.663,2026-07-31,22:00:00,N,2,NaN,2026-07-31 22:00:00,1.0,2026-07-31 22:00:00 (25507),1.0,

In [19]:
user_df = df[['mars_userid', 'RestaurantID']].groupby('mars_userid').nunique().reset_index()
user_df.columns=['mars_userid', 'UniquePOICount']
user_df

        mars_userid  UniquePOICount
0               111               1
1               114               1
2               127               1
3               132               1
4               142               2
...             ...             ...
257352      7646559               1
257353      7646562               1
257354      7646610               1
257355      7646636               1
257356      7646693               1

[257357 rows x 2 columns]

In [20]:
df = df.merge(user_df, on='mars_userid', suffixes=('', '_'))
df

,RestaurantID,RestaurantName,BookingRefId,mars_userid,SubmitTime,BookingDate,BookingTime,hv_noshow,AmendedSeat,bookmenu_spending,BookingDateTime,Rank,UniquePOICount
0,19826,後街牛扒,20260718065025,111,2026-07-18 18:24:40.597,2026-07-21,19:30:00,N,2,NaN,2026-07-21 19:30:00,1.0,1
1,27535,牛大人台灣火鍋吃到飽,20260721125459,114,2026-07-21 20:55:16.980,2026-07-23,11:30:00,N,2,NaN,2026-07-23 11:30:00,1.0,1
2,97080,Basic Bistro,20260718069701-1,127,2026-07-19 17:05:52.500,2026-07-19,20:30:00,N,2,NaN,2026-07-19 20:30:00,1.0,1
3,50493,喫茶ちょうぼ,20260710897474,132,2026-07-10 17:52:26.830,2026-07-11,15:30:00,N,4,NaN,2026-07-11 15:30:00,1.0,1
4,120282,Cooshti,20260729272886,142,2026-07-29 12:45:06.267,2026-07-29,18:30:00,N,5,NaN,2026-07-29 18:30:00,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
352062,52312,大滾友火鍋,20260731324491,7646559,2026-07-31 19:37:18.760,2026-07-31,20:00:00,N,3,NaN,2026-07-31 20:00:00,1.0,1
352063,125297,GOLDEN CAFE,20260731324521,7646562,2026-07-31 19:38:16.797,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,1
352064,93695,九五至尊火鍋狗毛,20260731326922-1,7646610,2026-07-31 21:54:10.370,2026-07-31,23:00:00,N,3,NaN,2026-07-31 23:00:00,1.0,1
352065,31944,KABOOM,20260731325255,7646636,2026-07-31 20:11:51.790,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,1
352066,25507,李家,20260731325572,7646693,2026-07-31 20:30:40.663,2026-07-31,22:00:00,N,2,NaN,2026-07-31 22:00:00,1.0,1

In [21]:
df = df.join(new_df[['Rank2', 'Target_Time']])
df

,RestaurantID,RestaurantName,BookingRefId,mars_userid,SubmitTime,BookingDate,BookingTime,hv_noshow,AmendedSeat,bookmenu_spending,BookingDateTime,Rank,UniquePOICount,Rank2,Target_Time
0,19826,後街牛扒,20260718065025,111,2026-07-18 18:24:40.597,2026-07-21,19:30:00,N,2,NaN,2026-07-21 19:30:00,1.0,1,1.0,
1,27535,牛大人台灣火鍋吃到飽,20260721125459,114,2026-07-21 20:55:16.980,2026-07-23,11:30:00,N,2,NaN,2026-07-23 11:30:00,1.0,1,1.0,
2,97080,Basic Bistro,20260718069701-1,127,2026-07-19 17:05:52.500,2026-07-19,20:30:00,N,2,NaN,2026-07-19 20:30:00,1.0,1,1.0,
3,50493,喫茶ちょうぼ,20260710897474,132,2026-07-10 17:52:26.830,2026-07-11,15:30:00,N,4,NaN,2026-07-11 15:30:00,1.0,1,1.0,
4,120282,Cooshti,20260729272886,142,2026-07-29 12:45:06.267,2026-07-29,18:30:00,N,5,NaN,2026-07-29 18:30:00,1.0,2,1.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352062,52312,大滾友火鍋,20260731324491,7646559,2026-07-31 19:37:18.760,2026-07-31,20:00:00,N,3,NaN,2026-07-31 20:00:00,1.0,1,1.0,
352063,125297,GOLDEN CAFE,20260731324521,7646562,2026-07-31 19:38:16.797,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,1,1.0,
352064,93695,九五至尊火鍋狗毛,20260731326922-1,7646610,2026-07-31 21:54:10.370,2026-07-31,23:00:00,N,3,NaN,2026-07-31 23:00:00,1.0,1,1.0,
352065,31944,KABOOM,20260731325255,7646636,2026-07-31 20:11:51.790,2026-07-31,21:00:00,N,2,NaN,2026-07-31 21:00:00,1.0,1,1.0,
352066,25507,李家,20260731325572,7646693,2026-07-31 20:30:40.663,2026-07-31,22:00:00,N,2,NaN,2026-07-31 22:00:00,1.0,1,1.0,

In [22]:
len(df[(df['UniquePOICount']>=2)]['mars_userid']), len(df[(df['UniquePOICount']>=2)]['mars_userid'].unique())

(147429, 57548)

In [23]:
#df.to_excel('offerid_400457_booking.xlsx',index=False)

In [24]:
#df.query("UniquePOICount>=6 and bookmenu_spending>0 and hv_noshow!='N'")

In [25]:
saved_report = 'BOOKMORE_Report_%s.xlsx'%(end_date)
df.query('UniquePOICount>=2').to_excel(saved_report)

In [26]:
# import traceback
# import requests
# ### function to send email
# def send_report(recipients):
#     url = 'http://edm.netcore.openrice.com/api/email/send'
#     headers = {'authorization': 'Bearer IJk_8wqgZPqe4X7a9lY980hulWt05DsAplPhgBqgT1Fygc1X28ZQnuHYzrtUFrHa4EB6KCSL7WmDs66cY11S7aBGGgw7g7SCbUAbVnT7bJntNqvwc_1suWROG_UJ9QTBot8R4tHdniUlt-Pi74q6Iz5dpaT-L82Iz56RuqMlktLgNIkWc9Spu4Owbf1vXsP0K-g0FLcbeaQ_YUzm4qg0LfXqL6O350t6R8t8xVVmVTP-HIaG37H3ggt-cggpxcKJ1fKYUgFuYV5RnvULCFziEcpDL5z1f6gBZauNa-_ZCT9ELpnEmlt9qrjnHHSPUBFf2jI0-PCBbBkeq113KJDDrOQpvto'}
#     data = {'Recipients': recipients,
#             'Sender': 'report@openrice.com',
#             'SenderName': 'Reporting System',
#             'Subject': 'BOOKMORE Report %s' %end_date,
#             'HtmlBody': '''
#                         Attached please find the BOOKMORE Report from %s to %s. If you have any inquiries.
#                         <br>
#                         <br>
#                         This is system generated email, please do not reply.
#                         <br>
#                         <br>
#                         OpenRice Data Analytics Team
#                         '''%(start_date, end_date)}
#     files = {'Attachment': open(saved_report, 'rb')}
#     res = requests.request('POST', url, data = data, headers = headers, files = files)
#     js = res.json()
#     if js['success'] == True:
#         print('sent email to %s' % recipients)
#     else:
#         print('fail to send email to %s' % recipients)
# send_report(['dandu@openrice.com';'angelapang@openrice.com'])

In [27]:
# if __name__ == '__main__':
#     print('process started')
#     try:
# #         send_report('kennyzhou@openrice.com')
#         send_report('angelapang@openrice.com; kimmylam@openrice.com')

#     except Exception as err:
#         tb = traceback.format_exc()
#         print('unexpected error: %s\n%s' % (str(err), tb))
#     print('process finished')

In [28]:
# with pymssql.connect(DB_info['server'], DB_info['user'], DB_info['password'], 'mars') as conn:
#     cursor = conn.cursor()
#     select_sql = '''
#     WITH booking_offer as (
#     SELECT distinct b.bookingid, o.offerid, o.TitleLang1 from booking b (NOLOCK)
#     LEFT JOIN offerwallet ow (NOLOCK) on b.bookingid = ow.bookingid
#     LEFT JOIN offer o (NOLOCK) on o.offerid = ow.offerid
#     left join poi p (NOLOCK) on b.poiid = p.poiid
#     left join openrice3.dbo.poi op (NOLOCK) on p.orpoiid = op.poiid
#     where ow.status=15 and b.status=10 and o.offerid = 278423 and b.userid!=0
#     and convert(date, b.bookingtime) between '2022-10-03' and '%s' and p.status not in (2,6)
#     ),
#     AIA_binding as (
#     SELECT userid from PartnerPromotionBinding pp (NOLOCK)
#     left join [user] u (NOLOCK) on u.ssouserid = pp.ssouserid
#     where pp.status=10 and pp.Type=4
#     )

#     SELECT  b.poiid as RestaurantID, p.namelang1 as RestaurantName, d.namelang1 as District, b.BookingRefId,
#     b.userid as mars_userid, ou.userid as or_userid, ou.username, b.DinerName,
#     iif(b.userid in (SELECT userid from AIA_binding), 'Y', 'N') as Binded_AIA, 
#     iif(b.PointType=1, b.point, null) as MilesPoint, iif(up.type=8 and up.status=10, up.point,null) as AIAtokens,
#     b.SubmitTime, convert(date,b.BookingTime) as BookingDate, convert(time, timeslottime) as BookingTime, b.modifytime,
#     b.Seat, b.AmendedSeat, b.IsDeposit,
#     case when BookingPaymentTransactionType=2 then bd.FinalPrice else null end as DepositTotalPrice,
#     bo.offerid, bo.titlelang1 as OfferTitle, 'promocode' as offertype,
#     bmo.BookingMenuId, bmo.Quantity as MenuQuantity, bmo.BookingMenuOrderId, 
#     case when bmo.status=3 then 'Refund'
#     when bmo.status=8 then 'Hold'
#     when bmo.status=10 then 'Active'
#     when bmo.status=15 then 'Redeemed' else null end as MenuStatus,
#     case when BookingPaymentTransactionType=1 then bd.FinalPrice else null end as MenuTotalPrice,
#     iif(b.StartTimeSlotId between 310 and 720, 'lunch','dinner') as meal,
#     case when b.BookingType=0 then 'Default'
#     when b.BookingType=1 then 'PrepaidOffer'
#     when b.BookingType=2 then 'ThirdParty'
#     when b.BookingType=3 then 'BookingWithMenu' else null end as bookingtype
#     from booking b (NOLOCK)
#     left join poi p (NOLOCK) on b.poiid = p.poiid
#     left join timeslot ts (NOLOCK) on b.StartTimeSlotId = ts.timeslotid
#     left join [user] u (NOLOCK) on b.userid = u.userid
#     left join openrice3.dbo.[user] ou (NOLOCK) on u.ssouserid = ou.ssouserid
#     left join district d (NOLOCK) on p.districtid = d.districtid
#     right join booking_offer bo on b.bookingid = bo.bookingid
#     left join UserPoint up (NOLOCK) on b.bookingid = up.itemid and up.type=8 and up.status=10
#     left join BookingPaymentTransaction bd (NOLOCK) on b.bookingid = bd.bookingid and bd.BookingPaymentTransactionType in (1,2) and bd.paymentstatus in (9,10)
#     left join BookingMenuOrder bmo (NOLOCK) on b.bookingid = bmo.bookingid and bmo.status in (3,8,10,15)
#     where p.status not in (2,6) and p.regionid=0 and b.userid!=0 and b.status=10
#     and convert(date, b.bookingtime) between '2022-10-03' and '%s'
#     order by u.userid , b.bookingid
#     '''%(str(end_date), str(end_date))
#     df = pd.read_sql(select_sql, conn)