In [133]:
# excel 前兩行數據
# MallCode,	OR_Landmark_ID,	MallNameTc,	MallNameEn,	Id,	OR_POI_ID,	ReferenceId,	MallId,	Name_en,	Name_tc,	Name_sc,	CategoryNameEn,	ShopNumber
# tmtplaza,	42,	屯門市廣場,	tmtplaza,	1592,	803423,	540,	1,	&you,	&you,	&you,	Western Cuisine,	3212
# tmtplaza,	42,	屯門市廣場,	tmtplaza,	1605,	794645,	544,	1,	A-1 Bakery Premium,	A-1 Bakery Premium,	A-1 Bakery Premium,	Confectionery & Deli,	UG046

# 我的需求如下
# 1. 讀取Sino POI full list.xlsx的sheet Sino POIs，統計每個landmark的每個orpoiid的以下數據：
# No. of POIs - Booking	
# No. of Booking	
# No. of POIs - Voucher	
# No. of Voucher Transaction	
# No. of POIs - Takeaway	
# No. of Takeaway Transaction	
# Retail POIs Video Views
# 計算邏輯代碼請參考 Sino_poi_stat.sql(請注意，代碼是基於landmark所有商戶統計的，我要的是在excel裏含有的poi：指定商戶)
# 我需要一次性呈現所有結果（像sql一樣），df只能有一個結果，不方便。
# 請保持SET @landmarkId = 37 的設定，我可以自己輸入landmark id生成結果。
# 有些orpoiid是空白的，這種情況請你refer to excel的Id欄，這是mars.dbo.poi的poiid （另外，mars.dbo.poi的orpoiid= openrice3.dbo.poi的poiid
# 有幾個landmarkid是NA，但是有商戶的id(=marspoiid),orpoiid信息，請你refer to excel的MallNameTc(landmark中文名字），cell2是excel例子，請你在所有結果df的顯示當前的landmark名字。
# 請確保輸出的marspoiid是excel的id欄對應的值

In [134]:
# MallCode,	OR_Landmark_ID,	MallNameTc,	MallNameEn,	Id,	OR_POI_ID,	ReferenceId,	MallId,	Name_en,	Name_tc,	Name_sc,	CategoryNameEn,	ShopNumber
# wanchai	N/A	灣仔	Wan Chai	1938	756721		12	Sugidama (The Hennessy)	杉玉居酒屋 (The Hennessy)	杉玉居酒屋 (The Hennessy)	Asian Cuisine	B&C
# wanchai	N/A	灣仔	Wan Chai	1943	31166		12	Wooloomooloo Steakhouse (The Hennessy)	Wooloomooloo Steakhouse (The Hennessy)	Wooloomooloo Steakhouse (The Hennessy)	Western Cuisine	1

In [135]:
import pandas as pd
import pymssql

DB_info = {'server': '192.168.61.119:7622', 'user': 'BAReporting', 'password': 'KeHeCReme8he'}

landmark_id = 42


manual_mall_name_tc = [
]
start_date = '2026-09-01'
end_date = '2026-10-01'

poi_source = pd.read_excel('Sino POI full list.xlsx', sheet_name='Sino POIs')
poi_data = poi_source.rename(columns={
    'OR Landmark ID': 'LandmarkId',
    'OR POI ID': 'ORPoiId',
    'Id': 'MarsPoiId',
}).copy()
poi_data['ORPoiId'] = poi_data['ORPoiId'].astype('string').str.strip().replace('', pd.NA)

def parse_or_poi_ids(value):
    if pd.isna(value):
        return []
    parsed_ids = []
    for value_part in str(value).split('/'):
        poi_id = pd.to_numeric(value_part.strip(), errors='coerce')
        if pd.notna(poi_id):
            parsed_ids.append(int(poi_id))
    return list(dict.fromkeys(parsed_ids))

poi_data['ORPoiIds'] = poi_data['ORPoiId'].map(parse_or_poi_ids)
for column in ['LandmarkId', 'MarsPoiId']:
    poi_data[column] = pd.to_numeric(poi_data[column], errors='coerce').astype('Int64')
for column in ['MallNameTc', 'Name_tc', 'Name_en']:
    poi_data[column] = poi_data[column].astype('string').str.strip().replace('', pd.NA)
poi_data['PoiName'] = poi_data['Name_tc'].fillna(poi_data['Name_en'])

if manual_mall_name_tc:
    selection = poi_data['MallNameTc'].isin(manual_mall_name_tc)
    missing_names = set(manual_mall_name_tc) - set(poi_data['MallNameTc'].dropna())
    if missing_names:
        raise ValueError(f'MallNameTc not found in Excel: {sorted(missing_names)}')
else:
    selection = poi_data['LandmarkId'].eq(landmark_id).fillna(False)

selected_poi_rows = (
    poi_data.loc[selection, ['LandmarkId', 'ORPoiId', 'ORPoiIds', 'MarsPoiId', 'MallNameTc', 'PoiName']]
    .dropna(subset=['ORPoiId', 'MarsPoiId'], how='all')
    .drop_duplicates(subset=['MallNameTc', 'ORPoiId', 'MarsPoiId'])
    .reset_index(drop=True)
)
selected_pois = selected_poi_rows.drop(columns='ORPoiIds')
if selected_pois.empty:
    raise ValueError('No POIs matched the selected landmark_id or manual_mall_name_tc values.')

selected_pois

    LandmarkId  ORPoiId  MarsPoiId MallNameTc                    PoiName
0           42   803423       1592      屯門市廣場                       &you
1           42   794645       1605      屯門市廣場         A-1 Bakery Premium
2           42     9527        582      屯門市廣場                        東海堂
3           42   858431       2058      屯門市廣場            b.o.t.h. eatery
4           42   690055       2383      屯門市廣場                Bamboo Thai
5           42   536564       1980      屯門市廣場                       霸嗎拉麺
6           42   733385       1502      屯門市廣場                         荳子
7           42   822773       1962      屯門市廣場               Beans Bakery
8           42   740672       1621      屯門市廣場                       BOVE
9           42  1108072       2353      屯門市廣場          Brava Java Coffee
10          42  1147773       2484      屯門市廣場                  泰出色甜品美食天地
11          42    17025        737      屯門市廣場                        大家樂
12          42   713537       <NA>      屯門市廣場   California Pizza Kitchen
13          42  1000362       2294      屯門市廣場                       霸王茶姬
14          42  1135744       2433      屯門市廣場                        皇甘栗
15          42  1129590       2430      屯門市廣場                        綠意坊
16          42   888192       2203      屯門市廣場                  四季椰林海南椰子雞
17          42   737862       1593      屯門市廣場                 COMEBUYTEA
18          42    25865        754      屯門市廣場                    翡翠拉麵小籠包
19          42   774224       2094      屯門市廣場                         稻成
20          42   474534        944      屯門市廣場                  大門 (Aeon)
21          42  1006386       2072      屯門市廣場                       十八里梅
22          42     <NA>       2158      屯門市廣場                   fufuland
23          42  1029858       2336      屯門市廣場               Ganto Gelato
24          42   534967        740      屯門市廣場                       元気壽司
25          42   732795       1721      屯門市廣場                    Gindaco
26          42   727325       1484      屯門市廣場                      金鳳大餐廳
27          42   575393        747      屯門市廣場                  牛角日本燒肉專門店
28          42   819851       1971      屯門市廣場                         牛繁
29          42  1114339       2461      屯門市廣場                        花丸軒
30          42   897937       2120      屯門市廣場                 厚興瑜記手撕雞專門店
31          42  1006393       1868      屯門市廣場                       海邊走走
32          42    21326        763      屯門市廣場                        海天堂
33          42   623120        902      屯門市廣場                      豪大大雞排
34          42     8126        577      屯門市廣場                        鴻福堂
35          42   748560       1614      屯門市廣場                       花甲年華
36          42   676908       1233      屯門市廣場                         皇玥
37          42    13233        949      屯門市廣場      Italian Tomato (Aeon)
38          42  1006407       2209      屯門市廣場                        JMT
39          42   835613       2023      屯門市廣場               K Chef Story
40          42   868548       2104      屯門市廣場                      甘味處鎌倉
41          42     9520        584      屯門市廣場                       奇華餅家
42          42   791183       1901      屯門市廣場     Komeda's Coffee (Aeon)
43          42   779806       2458      屯門市廣場                 La Famille
44          42  1002377       2338      屯門市廣場                       神燈會館
45          42  1114558       2349      屯門市廣場      LIFETASTIC Patisserie
46          42     <NA>       2048      屯門市廣場                   檸濛濛手打檸檬茶
47          42   642412        982      屯門市廣場                         龍島
48          42  1027542       2342      屯門市廣場                   馬記永蘭州牛肉麵
49          42  1106078       2392      屯門市廣場                         鰻丸
50          42  1119901       2391      屯門市廣場                       丸亀製麵
51          42  1029415       2333      屯門市廣場                         松屋
52          42    46838       2099      屯門市廣場                        麥當勞
53          42   680762       2478      屯門市廣場                       敏華冰廳
54          42   864827       2098      屯門市廣場                         明谷
55          42   539793        588      屯門市廣場                   Morozoff
56          42   669476       1185      屯門市廣場                         牛気
57          42  1008912       2346      屯門市廣場                      再睡5分鐘
58          42  1105278       2359      屯門市廣場                       肉肉大米
59          42   166560        947      屯門市廣場                 名點屋 (Aeon)
60          42   143148        757      屯門市廣場  Oliver's Super Sandwiches
61          42   777416       1745      屯門市廣場             Pacific Coffee
62          42   814263        585      屯門市廣場                     Panash
63          42   744350       1619      屯門市廣場               Pepper Lunch
64          42   701804       1362      屯門市廣場       PHI COFFEE & PANCAKE
65          42   791197       1869      屯門市廣場                 Pizza Maru
66          42  1105945       2367      屯門市廣場                       拉麵太郎
67          42  1006442       1617      屯門市廣場                       櫻木食堂
68          42   739527       1644      屯門市廣場                     山見台式火鍋
69          42  1006449       2153      屯門市廣場                        上稀園
70          42  1004492       2302      屯門市廣場                        三兩粉
71          42    20286       1496      屯門市廣場                        星巴克
72          42   899217       2259      屯門市廣場                    御滿屋日本料理
73          42   690962       1321      屯門市廣場                        壽司郎
74          42   490373       2065      屯門市廣場                         爭鮮
75          42   834792       2095      屯門市廣場                       台北食堂
76          42   744651       1618      屯門市廣場                    千味家健康食堂
77          42   474921        739      屯門市廣場                         茶木
78          42   744898       1646      屯門市廣場         Terrace in seaside
79          42   683758       1260      屯門市廣場                    牧羊少年咖啡館
80          42   766787       1720      屯門市廣場           The Matcha Toyko
81          42   878511       2152      屯門市廣場                         泰雅
82          42  1142611       2459      屯門市廣場                        添好運
83          42   883399       2199      屯門市廣場                        鳥貴族
84          42   895483       2222      屯門市廣場                    靠得住粥麵小館
85          42   713141       1380      屯門市廣場     UCC Coffee Shop (Aeon)
86          42   896415       2145      屯門市廣場                     Venchi
87          42  1006477       1316      屯門市廣場                       偉成洋酒
88          42   864137       2075      屯門市廣場                       永年士多
89          42   446095        591      屯門市廣場                       榮華餅家
90          42   739520       1643      屯門市廣場                      佐賀燒肉谷

In [136]:
metric_columns = [
    'No. of POIs - Booking',
    'No. of Booking',
    'No. of POIs - Voucher',
    'No. of Voucher Transaction',
    'No. of POIs - Takeaway',
    'No. of Takeaway Transaction',
    'Retail POIs Video Views',
]


def metric_select(scope):
    bbo_scope = f'SELECT BboMarsPoiId FROM #MappedPoi WHERE {scope}'
    video_scope = f'SELECT OpenRicePoiId FROM #MappedPoi WHERE {scope}'
    return f'''
    (SELECT COUNT(DISTINCT booking.PoiId) FROM mars.dbo.Booking AS booking
     WHERE booking.BookingTime > @START AND booking.BookingTime < @END
       AND booking.[Status] = 10 AND booking.PoiId IN ({bbo_scope})),
    (SELECT COUNT_BIG(*) FROM mars.dbo.Booking AS booking
     WHERE booking.BookingTime > @START AND booking.BookingTime < @END
       AND booking.[Status] = 10 AND booking.PoiId IN ({bbo_scope})),
    (SELECT COUNT(DISTINCT poi.NameLang1)
     FROM mars.dbo.Poi AS poi
     INNER JOIN mars.dbo.BizService AS service ON service.PoiId = poi.PoiId
     WHERE service.ServiceStartTime < @END AND service.ServiceEndTime >= @END
       AND service.ServiceTypeId = 5 AND poi.PoiId IN ({bbo_scope})),
    (SELECT COUNT(DISTINCT offer_poi.PoiId)
     FROM mars.dbo.OfferWallet AS wallet
     INNER JOIN mars.dbo.OfferPoi AS offer_poi ON offer_poi.OfferId = wallet.OfferId
     INNER JOIN mars.dbo.Offer AS offer ON offer.OfferId = offer_poi.OfferId
     WHERE wallet.CreateTime > @START AND wallet.CreateTime < @END
       AND wallet.[Status] = 15 AND offer.OfferType IN (7, 18, 22)
       AND offer_poi.PoiId IN ({bbo_scope}) AND wallet.RedeemPoiId IN ({bbo_scope})),
    (SELECT COUNT(DISTINCT takeaway.PoiId)
     FROM mars.dbo.TakeAwayOrder AS takeaway WITH (NOLOCK)
     WHERE takeaway.TakeAwayOrderId >= @MIN_TakeAwayOrderID
       AND takeaway.CreateTime < @END AND takeaway.[Status] = 10
       AND takeaway.PoiId IN ({bbo_scope})),
    (SELECT COUNT_BIG(*) FROM mars.dbo.TakeAwayOrder AS takeaway WITH (NOLOCK)
     WHERE takeaway.TakeAwayOrderId >= @MIN_TakeAwayOrderID
       AND takeaway.CreateTime < @END AND takeaway.[Status] = 10
       AND takeaway.PoiId IN ({bbo_scope})),
    (SELECT COALESCE(SUM(media.HitCount), 0)
     FROM openrice3.dbo.Media AS media
     INNER JOIN openrice3.dbo.Poi AS poi ON poi.PoiId = media.PoiId
     WHERE poi.PoiTypeId = 10 AND media.PoiId IN ({video_scope}))
    '''


sql = f'''
SET NOCOUNT ON;
DECLARE @START datetime = %s;
DECLARE @END datetime = %s;

SELECT DISTINCT
    excel.RowId,
    excel.MallNameTc,
    bbo.PoiId AS BboMarsPoiId,
    COALESCE(excel_or.ORPoiId, bbo.ORPoiId) AS OpenRicePoiId
INTO #MappedPoi
FROM #ExcelPoi AS excel
LEFT JOIN #ExcelPoiORId AS excel_or ON excel_or.RowId = excel.RowId
LEFT JOIN mars.dbo.Poi AS bbo
    ON (excel_or.ORPoiId IS NOT NULL AND excel_or.ORPoiId = bbo.ORPoiId AND bbo.RegionId = 0
        AND EXISTS (SELECT 1 FROM openrice3.dbo.Poi AS poi
                    WHERE poi.PoiId = excel_or.ORPoiId AND poi.[Status] IN (3, 10)))
    OR (excel_or.ORPoiId IS NULL AND excel.MarsPoiId = bbo.PoiId);

DECLARE @MIN_TakeAwayOrderID int;
SELECT @MIN_TakeAwayOrderID = MAX(TakeAwayOrderID)
FROM mars.dbo.TakeAwayOrder WITH (NOLOCK)
WHERE CreateTime < @START;

SELECT excel.RowId, CAST(NULL AS nvarchar(255)) AS SummaryMallNameTc,
       {metric_select('RowId = excel.RowId')}
FROM #ExcelPoi AS excel
UNION ALL
SELECT -ROW_NUMBER() OVER (ORDER BY summary.MallNameTc), summary.MallNameTc,
       {metric_select('MallNameTc = summary.MallNameTc')}
FROM (SELECT DISTINCT MallNameTc FROM #ExcelPoi) AS summary
ORDER BY RowId;
'''

input_rows = [
    (
        row_id,
        int(mars_poi_id) if pd.notna(mars_poi_id) else None,
        str(mall_name) if pd.notna(mall_name) else None,
    )
    for row_id, (mars_poi_id, mall_name) in enumerate(
        selected_pois[['MarsPoiId', 'MallNameTc']].itertuples(index=False, name=None)
    )
]
input_or_rows = [
    (row_id, or_poi_id)
    for row_id, poi_ids in enumerate(selected_poi_rows['ORPoiIds'])
    for or_poi_id in poi_ids
]
with pymssql.connect(**DB_info) as conn:
    with conn.cursor() as cursor:
        cursor.execute(
            'CREATE TABLE #ExcelPoi '
            '(RowId int PRIMARY KEY, MarsPoiId int NULL, MallNameTc nvarchar(255) NULL);'
        )
        cursor.executemany('INSERT INTO #ExcelPoi VALUES (%s, %s, %s)', input_rows)
        cursor.execute(
            'CREATE TABLE #ExcelPoiORId (RowId int NOT NULL, ORPoiId int NOT NULL, '
            'PRIMARY KEY (RowId, ORPoiId));'
        )
        if input_or_rows:
            cursor.executemany(
                'INSERT INTO #ExcelPoiORId (RowId, ORPoiId) VALUES (%s, %s)',
                input_or_rows,
            )
        cursor.execute(sql, (start_date, end_date))
        metrics = pd.DataFrame(
            cursor.fetchall(),
            columns=['RowId', 'SummaryMallNameTc'] + metric_columns,
        )

poi_report = selected_pois.copy()
poi_report.insert(0, 'RowId', range(len(poi_report)))
poi_report = poi_report.merge(
    metrics.loc[metrics['RowId'].ge(0), ['RowId'] + metric_columns],
    on='RowId',
    validate='one_to_one',
)
poi_report = poi_report.drop(columns='RowId')
poi_report.insert(0, 'LandmarkNameTc', poi_report['MallNameTc'])

summary = metrics.loc[metrics['RowId'].lt(0)].copy()
summary['MallNameTc'] = summary['SummaryMallNameTc']
summary['LandmarkNameTc'] = summary['SummaryMallNameTc']
summary['PoiName'] = 'COUNT ALL'
summary['LandmarkId'] = pd.NA
summary['ORPoiId'] = pd.NA
summary['MarsPoiId'] = pd.NA
summary = summary.drop(columns=['RowId', 'SummaryMallNameTc'])
report = pd.concat([poi_report, summary[poi_report.columns]], ignore_index=True)
report = report.astype({'LandmarkId': 'Int64', 'MarsPoiId': 'Int64'})

assert len(poi_report) == len(selected_pois)
assert poi_report['MarsPoiId'].equals(selected_pois['MarsPoiId'])
assert poi_report['ORPoiId'].equals(selected_pois['ORPoiId'])
assert poi_report['PoiName'].equals(selected_pois['PoiName'])
assert len(summary) == selected_pois['MallNameTc'].nunique(dropna=False)
print(f'POI data count all: {len(poi_report)}; summary rows: {len(summary)}')

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
report

POI data count all: 91; summary rows: 1

,LandmarkNameTc,LandmarkId,ORPoiId,MarsPoiId,MallNameTc,PoiName,No. of POIs - Booking,No. of Booking,No. of POIs - Voucher,No. of Voucher Transaction,No. of POIs - Takeaway,No. of Takeaway Transaction,Retail POIs Video Views
0,屯門市廣場,42,803423,1592,屯門市廣場,&you,0,0,1,0,0,0,0
1,屯門市廣場,42,794645,1605,屯門市廣場,A-1 Bakery Premium,0,0,0,0,0,0,0
2,屯門市廣場,42,9527,582,屯門市廣場,東海堂,0,0,1,0,0,0,0
3,屯門市廣場,42,858431,2058,屯門市廣場,b.o.t.h. eatery,1,221,0,0,1,1,0
4,屯門市廣場,42,690055,2383,屯門市廣場,Bamboo Thai,1,124,1,0,1,5,0
5,屯門市廣場,42,536564,1980,屯門市廣場,霸嗎拉麺,1,8,0,0,1,9,0
6,屯門市廣場,42,733385,1502,屯門市廣場,荳子,0,0,1,0,0,0,0
7,屯門市廣場,42,822773,1962,屯門市廣場,Beans Bakery,0,0,0,0,0,0,0
8,屯門市廣場,42,740672,1621,屯門市廣場,BOVE,0,0,0,0,0,0,0
9,屯門市廣場,42,1108072,2353,屯門市廣場,Brava Java Coffee,0,0,0,0,1,4,0
10,屯門市廣場,42,1147773,2484,屯門市廣場,泰出色甜品美食天地,0,0,0,0,0,0,0
11,屯門市廣場,42,17025,737,屯門市廣場,大家樂,0,0,1,0,0,0,0
12,屯門市廣場,42,713537,<NA>,屯門市廣場,California Pizza Kitchen,1,61,0,0,1,2,0
13,屯門市廣場,42,1000362,2294,屯門市廣場,霸王茶姬,0,0,0,0,0,0,0
14,屯門市廣場,42,1135744,2433,屯門市廣場,皇甘栗,0,0,0,0,0,0,0
15,屯門市廣場,42,1129590,2430,屯門市廣場,綠意坊,1,13,0,0,0,0,0
16,屯門市廣場,42,888192,2203,屯門市廣場,四季椰林海南椰子雞,1,215,1,1,1,7,0
17,屯門市廣場,42,737862,1593,屯門市廣場,COMEBUYTEA,0,0,0,0,0,0,0
18,屯門市廣場,42,25865,754,屯門市廣場,翡翠拉麵小籠包,1,151,0,0,0,0,0
19,屯門市廣場,42,774224,2094,屯門市廣場,稻成,1,175,1,0,1,8,0
20,屯門市廣場,42,474534,944,屯門市廣場,大門 (Aeon),0,0,0,0,1,7,0
21,屯門市廣場,42,1006386,2072,屯門市廣場,十八里梅,0,0,0,0,0,0,0
22,屯門市廣場,42,<NA>,2158,屯門市廣場,fufuland,0,0,0,0,0,0,0
23,屯門市廣場,42,1029858,2336,屯門市廣場,Ganto Gelato,0,0,0,0,0,0,0
24,屯門市廣場,42,534967,740,屯門市廣場,元気壽司,0,0,1,0,0,0,0
25,屯門市廣場,42,732795,1721,屯門市廣場,Gindaco,0,0,0,0,0,0,0
26,屯門市廣場,42,727325,1484,屯門市廣場,金鳳大餐廳,0,0,0,0,1,65,0
27,屯門市廣場,42,575393,747,屯門市廣場,牛角日本燒肉專門店,0,0,0,0,0,0,0
28,屯門市廣場,42,819851,1971,屯門市廣場,牛繁,0,0,0,0,0,0,0
29,屯門市廣場,42,1114339,2461,屯門市廣場,花丸軒,0,0,0,0,0,0,0
30,屯門市廣場,42,897937,2120,屯門市廣場,厚興瑜記手撕雞專門店,0,0,0,0,0,0,0
31,屯門市廣場,42,1006393,1868,屯門市廣場,海邊走走,0,0,0,0,0,0,0
32,屯門市廣場,42,21326,763,屯門市廣場,海天堂,0,0,1,0,0,0,0
33,屯門市廣場,42,623120,902,屯門市廣場,豪大大雞排,0,0,0,0,0,0,0
34,屯門市廣場,42,8126,577,屯門市廣場,鴻福堂,0,0,1,0,0,0,0
35,屯門市廣場,42,748560,1614,屯門市廣場,花甲年華,0,0,0,0,0,0,0
36,屯門市廣場,42,676908,1233,屯門市廣場,皇玥,0,0,1,0,0,0,0
37,屯門市廣場,42,13233,949,屯門市廣場,Italian Tomato (Aeon),0,0,1,0,0,0,0
38,屯門市廣場,42,1006407,2209,屯門市廣場,JMT,0,0,0,0,0,0,0
39,屯門市廣場,42,835613,2023,屯門市廣場,K Chef Story,0,0,0,0,1,12,0
40,屯門市廣場,42,868548,2104,屯門市廣場,甘味處鎌倉,0,0,0,0,0,0,0
41,屯門市廣場,42,9520,584,屯門市廣場,奇華餅家,0,0,1,0,0,0,0
42,屯門市廣場,42,791183,1901,屯門市廣場,Komeda's Coffee (Aeon),0,0,0,0,0,0,0
43,屯門市廣場,42,779806,2458,屯門市廣場,La Famille,0,0,0,0,0,0,0
44,屯門市廣場,42,1002377,2338,屯門市廣場,神燈會館,0,0,0,0,0,0,0
45,屯門市廣場,42,1114558,2349,屯門市廣場,LIFETASTIC Patisserie,0,0,0,0,0,0,0
46,屯門市廣場,42,<NA>,2048,屯門市廣場,檸濛濛手打檸檬茶,0,0,0,0,0,0,0
47,屯門市廣場,42,642412,982,屯門市廣場,龍島,0,0,0,0,0,0,0
48,屯門市廣場,42,1027542,2342,屯門市廣場,馬記永蘭州牛肉麵,0,0,0,0,0,0,0
49,屯門市廣場,42,1106078,2392,屯門市廣場,鰻丸,0,0,0,0,0,0,0
50,屯門市廣場,42,1119901,2391,屯門市廣場,丸亀製麵,0,0,0,0,0,0,0
51,屯門市廣場,42,1029415,2333,屯門市廣場,松屋,0,0,0,0,0,0,0
52,屯門市廣場,42,46838,2099,屯門市廣場,麥當勞,0,0,0,0,0,0,0
53,屯門市廣場,42,680762,2478,屯門市廣場,敏華冰廳,0,0,1,0,0,0,0
54,屯門市廣場,42,864827,2098,屯門市廣場,明谷,0,0,1,0,0,0,0
55,屯門市廣場,42,539793,588,屯門市廣場,Morozoff,0,0,0,0,0,0,0
56,屯門市廣場,42,669476,1185,屯門市廣場,牛気,1,156,1,0,0,0,0
57,屯門市廣場,42,1008912,2346,屯門市廣場,再睡5分鐘,0,0,0,0,0,0,0
58,屯門市廣場,42,1105278,2359,屯門市廣場,肉肉大米,0,0,0,0,0,0,0
59,屯門市廣場,42,166560,947,屯門市廣場,名點屋 (Aeon),0,0,0,0,0,0,0
60,屯門市廣場,42,143148,757,屯門市廣場,Oliver's Super Sandwiches,0,0,0,0,0,0,0
61,屯門市廣場,42,777416,1745,屯門市廣場,Pacific Coffee,0,0,0,0,0,0,0
62,屯門市廣場,42,814263,585,屯門市廣場,Panash,0,0,0,0,0,0,0
63,屯門市廣場,42,744350,1619,屯門市廣場,Pepper Lunch,0,0,0,0,0,0,0
64,屯門市廣場,42,701804,1362,屯門市廣場,PHI COFFEE & PANCAKE,0,0,0,0,1,15,0
65,屯門市廣場,42,791197,1869,屯門市廣場,Pizza Maru,0,0,0,0,0,0,0
66,屯門市廣場,42,1105945,2367,屯門市廣場,拉麵太郎,0,0,0,0,0,0,0
67,屯門市廣場,42,1006442,1617,屯門市廣場,櫻木食堂,0,0,0,0,0,0,0
68,屯門市廣場,42,739527,1644,屯門市廣場,山見台式火鍋,1,95,1,0,0,0,0
69,屯門市廣場,42,1006449,2153,屯門市廣場,上稀園,0,0,0,0,0,0,0
70,屯門市廣場,42,1004492,2302,屯門市廣場,三兩粉,0,0,0,0,0,0,0
71,屯門市廣場,42,20286,1496,屯門市廣場,星巴克,0,0,1,0,0,0,0
72,屯門市廣場,42,899217,2259,屯門市廣場,御滿屋日本料理,0,0,1,0,0,0,0
73,屯門市廣場,42,690962,1321,屯門市廣場,壽司郎,0,0,0,0,0,0,0
74,屯門市廣場,42,490373,2065,屯門市廣場,爭鮮,0,0,1,0,0,0,0
75,屯門市廣場,42,834792,2095,屯門市廣場,台北食堂,0,0,1,0,1,2,0
76,屯門市廣場,42,744651,1618,屯門市廣場,千味家健康食堂,0,0,0,0,0,0,0
77,屯門市廣場,42,474921,739,屯門市廣場,茶木,0,0,1,0,0,0,0
78,屯門市廣場,42,744898,1646,屯門市廣場,Terrace in seaside,0,0,0,0,1,4,0
79,屯門市廣場,42,683758,1260,屯門市廣場,牧羊少年咖啡館,0,0,0,0,1,37,0
80,屯門市廣場,42,766787,1720,屯門市廣場,The Matcha Toyko,0,0,0,0,1,5,0
81,屯門市廣場,42,878511,2152,屯門市廣場,泰雅,0,0,0,0,0,0,0
82,屯門市廣場,42,1142611,2459,屯門市廣場,添好運,0,0,0,0,0,0,0
83,屯門市廣場,42,883399,2199,屯門市廣場,鳥貴族,0,0,0,0,0,0,0
84,屯門市廣場,42,895483,2222,屯門市廣場,靠得住粥麵小館,0,0,0,0,0,0,0
85,屯門市廣場,42,713141,1380,屯門市廣場,UCC Coffee Shop (Aeon),0,0,0,0,0,0,0
86,屯門市廣場,42,896415,2145,屯門市廣場,Venchi,0,0,0,0,0,0,0
87,屯門市廣場,42,1006477,1316,屯門市廣場,偉成洋酒,0,0,0,0,0,0,0
88,屯門市廣場,42,864137,2075,屯門市廣場,永年士多,0,0,0,0,0,0,0
89,屯門市廣場,42,446095,591,屯門市廣場,榮華餅家,0,0,0,0,0,0,0
90,屯門市廣場,42,739520,1643,屯門市廣場,佐賀燒肉谷,1,173,1,0,0,0,0
91,屯門市廣場,<NA>,<NA>,<NA>,屯門市廣場,COUNT ALL,11,1392,23,1,15,183,0

In [137]:
# extreme case 
# MallCode,	OR_Landmark_ID,	MallNameTc,	MallNameEn,	Id,	OR_POI_ID,	ReferenceId,	MallId,	Name_en,	Name_tc,	Name_sc,	CategoryNameEn,	ShopNumber
# citywalk,	65,	荃新天地,	Citywalk,	1430,	714892 / 711644,	287,	2,	Cha Thai / Chicken Factory,	茶泰 / Chicken Factory,	茶泰 / Chicken Factory,	Asian Cuisine,	UG81

In [138]:
poi_input_rows = [
    (
        row_id,
        int(mars_poi_id) if pd.notna(mars_poi_id) else None,
        str(or_poi_id) if pd.notna(or_poi_id) else None,
        str(mall_name) if pd.notna(mall_name) else None,
        str(poi_name) if pd.notna(poi_name) else None,
    )
    for row_id, (mars_poi_id, or_poi_id, mall_name, poi_name) in enumerate(
        selected_pois[['MarsPoiId', 'ORPoiId', 'MallNameTc', 'PoiName']].itertuples(index=False, name=None)
    )
]
poi_or_id_rows = [
    (row_id, or_poi_id)
    for row_id, poi_ids in enumerate(selected_poi_rows['ORPoiIds'])
    for or_poi_id in poi_ids
]

list_sql = '''
SET NOCOUNT ON;
DECLARE @START datetime = %s;
DECLARE @END datetime = %s;

CREATE TABLE #MappedPoi (
    RowId int NOT NULL,
    ORPoiIdOriginal nvarchar(100) NULL,
    ExcelMarsPoiId int NULL,
    MallNameTc nvarchar(255) NULL,
    PoiName nvarchar(255) NULL,
    BboMarsPoiId int NULL,
    OpenRicePoiId int NULL
);

INSERT INTO #MappedPoi (RowId, ORPoiIdOriginal, ExcelMarsPoiId, MallNameTc, PoiName, BboMarsPoiId, OpenRicePoiId)
SELECT DISTINCT
    excel.RowId,
    excel.ORPoiIdOriginal,
    excel.MarsPoiId,
    excel.MallNameTc,
    excel.PoiName,
    bbo.PoiId,
    COALESCE(excel_or.ORPoiId, bbo.ORPoiId)
FROM #ExcelPoi AS excel
LEFT JOIN #ExcelPoiORId AS excel_or ON excel_or.RowId = excel.RowId
LEFT JOIN mars.dbo.Poi AS bbo
    ON (excel_or.ORPoiId IS NOT NULL AND excel_or.ORPoiId = bbo.ORPoiId AND bbo.RegionId = 0)
    OR (excel_or.ORPoiId IS NULL AND excel.MarsPoiId = bbo.PoiId);

DECLARE @MIN_TakeAwayOrderID int;
SELECT @MIN_TakeAwayOrderID = MAX(TakeAwayOrderId)
FROM mars.dbo.TakeAwayOrder WITH (NOLOCK)
WHERE CreateTime < @START;

;WITH PoiLists AS (
    SELECT DISTINCT
        Category = CAST('Booking' AS nvarchar(30)),
        mapped.RowId,
        mapped.MallNameTc,
        mapped.ExcelMarsPoiId AS MarsPoiId,
        mapped.ORPoiIdOriginal AS ORPoiId,
        mapped.PoiName,
        Views = CAST(NULL AS bigint)
    FROM #MappedPoi AS mapped
    INNER JOIN mars.dbo.Booking AS booking ON booking.PoiId = mapped.BboMarsPoiId
    INNER JOIN mars.dbo.BizService AS service ON service.PoiId = mapped.BboMarsPoiId
    WHERE booking.BookingTime > @START
      AND booking.BookingTime < @END
      AND booking.[Status] = 10

    UNION ALL

    SELECT DISTINCT
        CAST('Voucher' AS nvarchar(30)),
        mapped.RowId,
        mapped.MallNameTc,
        mapped.ExcelMarsPoiId,
        mapped.ORPoiIdOriginal,
        mapped.PoiName,
        CAST(NULL AS bigint)
    FROM #MappedPoi AS mapped
    INNER JOIN mars.dbo.Poi AS poi ON poi.PoiId = mapped.BboMarsPoiId
    INNER JOIN mars.dbo.BizService AS service ON service.PoiId = poi.PoiId
    WHERE service.ServiceStartTime < @END
      AND service.ServiceEndTime >= @END
      AND service.ServiceTypeId = 5

    UNION ALL

    SELECT DISTINCT
        CAST('TAS' AS nvarchar(30)),
        mapped.RowId,
        mapped.MallNameTc,
        mapped.ExcelMarsPoiId,
        mapped.ORPoiIdOriginal,
        mapped.PoiName,
        CAST(NULL AS bigint)
    FROM #MappedPoi AS mapped
    INNER JOIN mars.dbo.Poi AS poi ON poi.PoiId = mapped.BboMarsPoiId
    INNER JOIN mars.dbo.BizService AS service ON service.PoiId = poi.PoiId
    INNER JOIN mars.dbo.TakeAwayOrder AS takeaway WITH (NOLOCK) ON takeaway.PoiId = poi.PoiId
    WHERE service.ServiceStartTime < @END
      AND service.ServiceEndTime >= @END
      AND service.ServiceTypeId = 4
      AND takeaway.TakeAwayOrderId >= @MIN_TakeAwayOrderID
      AND takeaway.CreateTime < @END
      AND takeaway.[Status] = 10

    UNION ALL

    SELECT
        CAST('Retail Video Views' AS nvarchar(30)),
        mapped.RowId,
        mapped.MallNameTc,
        mapped.ExcelMarsPoiId,
        mapped.ORPoiIdOriginal,
        mapped.PoiName,
        COALESCE(SUM(media.HitCount), 0)
    FROM (
        SELECT DISTINCT RowId, MallNameTc, ExcelMarsPoiId, ORPoiIdOriginal, PoiName, OpenRicePoiId
        FROM #MappedPoi
        WHERE OpenRicePoiId IS NOT NULL
    ) AS mapped
    INNER JOIN openrice3.dbo.Poi AS poi ON poi.PoiId = mapped.OpenRicePoiId
    LEFT JOIN openrice3.dbo.Media AS media ON media.PoiId = poi.PoiId
    WHERE poi.PoiTypeId = 10
    GROUP BY mapped.RowId, mapped.MallNameTc, mapped.ExcelMarsPoiId,
             mapped.ORPoiIdOriginal, mapped.PoiName
)
SELECT
    Category,
    MallNameTc AS LandmarkNameTc,
    MarsPoiId,
    ORPoiId,
    PoiName,
    Views
FROM PoiLists
ORDER BY Category, MallNameTc, PoiName, RowId;
'''

with pymssql.connect(**DB_info) as conn:
    with conn.cursor() as cursor:
        cursor.execute(
            'CREATE TABLE #ExcelPoi '
            '(RowId int NOT NULL PRIMARY KEY, MarsPoiId int NULL, ORPoiIdOriginal nvarchar(100) NULL, '
            'MallNameTc nvarchar(255) NULL, PoiName nvarchar(255) NULL);'
        )
        cursor.executemany(
            'INSERT INTO #ExcelPoi (RowId, MarsPoiId, ORPoiIdOriginal, MallNameTc, PoiName) '
            'VALUES (%s, %s, %s, %s, %s)',
            poi_input_rows,
        )
        cursor.execute(
            'CREATE TABLE #ExcelPoiORId (RowId int NOT NULL, ORPoiId int NOT NULL, '
            'PRIMARY KEY (RowId, ORPoiId));'
        )
        if poi_or_id_rows:
            cursor.executemany(
                'INSERT INTO #ExcelPoiORId (RowId, ORPoiId) VALUES (%s, %s)',
                poi_or_id_rows,
            )
        cursor.execute(list_sql, (start_date, end_date))
        poi_list_df = pd.DataFrame.from_records(
            cursor.fetchall(),
            columns=[column[0] for column in cursor.description],
        )

poi_list_df = poi_list_df.astype({'MarsPoiId': 'Int64'})
booking_list = poi_list_df.loc[poi_list_df['Category'].eq('Booking')].reset_index(drop=True)
voucher_list = poi_list_df.loc[poi_list_df['Category'].eq('Voucher')].reset_index(drop=True)
takeaway_list = poi_list_df.loc[poi_list_df['Category'].eq('TAS')].reset_index(drop=True)
retail_video_views_list = poi_list_df.loc[
    poi_list_df['Category'].eq('Retail Video Views')
].reset_index(drop=True)

poi_list_df

   Category LandmarkNameTc  MarsPoiId  ORPoiId                   PoiName Views
0   Booking          屯門市廣場       2058   858431           b.o.t.h. eatery  None
1   Booking          屯門市廣場       2383   690055               Bamboo Thai  None
2   Booking          屯門市廣場       <NA>   713537  California Pizza Kitchen  None
3   Booking          屯門市廣場       1643   739520                     佐賀燒肉谷  None
4   Booking          屯門市廣場       2203   888192                 四季椰林海南椰子雞  None
5   Booking          屯門市廣場       1644   739527                    山見台式火鍋  None
6   Booking          屯門市廣場       1185   669476                        牛気  None
7   Booking          屯門市廣場       2094   774224                        稻成  None
8   Booking          屯門市廣場       2430  1129590                       綠意坊  None
9   Booking          屯門市廣場        754    25865                   翡翠拉麵小籠包  None
10  Booking          屯門市廣場       1980   536564                      霸嗎拉麺  None
11      TAS          屯門市廣場       2058   858431           b.o.t.h. eatery  None
12      TAS          屯門市廣場       2383   690055               Bamboo Thai  None
13      TAS          屯門市廣場       2353  1108072         Brava Java Coffee  None
14      TAS          屯門市廣場       <NA>   713537  California Pizza Kitchen  None
15      TAS          屯門市廣場       2023   835613              K Chef Story  None
16      TAS          屯門市廣場       1362   701804      PHI COFFEE & PANCAKE  None
17      TAS          屯門市廣場       1646   744898        Terrace in seaside  None
18      TAS          屯門市廣場       1720   766787          The Matcha Toyko  None
19      TAS          屯門市廣場       2095   834792                      台北食堂  None
20      TAS          屯門市廣場       2203   888192                 四季椰林海南椰子雞  None
21      TAS          屯門市廣場        944   474534                 大門 (Aeon)  None
22      TAS          屯門市廣場       1260   683758                   牧羊少年咖啡館  None
23      TAS          屯門市廣場       2094   774224                        稻成  None
24      TAS          屯門市廣場       1484   727325                     金鳳大餐廳  None
25      TAS          屯門市廣場       1980   536564                      霸嗎拉麺  None
26  Voucher          屯門市廣場       1592   803423                      &you  None
27  Voucher          屯門市廣場       2383   690055               Bamboo Thai  None
28  Voucher          屯門市廣場        949    13233     Italian Tomato (Aeon)  None
29  Voucher          屯門市廣場       1643   739520                     佐賀燒肉谷  None
30  Voucher          屯門市廣場        740   534967                      元気壽司  None
31  Voucher          屯門市廣場       2095   834792                      台北食堂  None
32  Voucher          屯門市廣場       2203   888192                 四季椰林海南椰子雞  None
33  Voucher          屯門市廣場        737    17025                       大家樂  None
34  Voucher          屯門市廣場        584     9520                      奇華餅家  None
35  Voucher          屯門市廣場       1644   739527                    山見台式火鍋  None
36  Voucher          屯門市廣場       2259   899217                   御滿屋日本料理  None
37  Voucher          屯門市廣場       2478   680762                      敏華冰廳  None
38  Voucher          屯門市廣場       2098   864827                        明谷  None
39  Voucher          屯門市廣場       1496    20286                       星巴克  None
40  Voucher          屯門市廣場        582     9527                       東海堂  None
41  Voucher          屯門市廣場        763    21326                       海天堂  None
42  Voucher          屯門市廣場       2065   490373                        爭鮮  None
43  Voucher          屯門市廣場       1185   669476                        牛気  None
44  Voucher          屯門市廣場       1233   676908                        皇玥  None
45  Voucher          屯門市廣場       2094   774224                        稻成  None
46  Voucher          屯門市廣場        739   474921                        茶木  None
47  Voucher          屯門市廣場       1502   733385                        荳子  None
48  Voucher          屯門市廣場        577     8126                       鴻福堂  None